### ISSUE TITLE
Could you provide a example for `SendDocument`

### ISSUE THREAD

**Issue by dhcmrlchtdj** [uonr/telegram-types#11]
https://github.com/uonr/telegram-types/blob/839158722ab3450928dfe8152d323bd1ecaa5bc9/src/bot/types.rs#L877-L883
The InputFile accepts a string only.
How to attach a filepath or a struct with filename and bytes?

And what is the 'attach://' scheme for?

**Comment by uonr** [comment]
According Telegram Bot Document

> File to send. Pass a file_id to send a file that exists on the Telegram servers (recommended), pass an HTTP URL for Telegram to get a file from the Internet, or pass “attach://<file_attach_name>” to upload a new one using multipart/form-data under <file_attach_name> name.

To upload a file, you need use `FileToSend` enum build url quest, and use POST request with the body encoding by `multipart/form-data`.

**Comment by uonr** [comment]
I'll add a new example...
